config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  resources :users do
    resources :posts do
      resource :likes, only: %i[create destroy]
    end
  end
  resources :users do
    resources :posts do
      resources :comments, only: [:create]
    end
  end
  resources :users do
    resources :posts do
      resources :comments, only: %i[new create] # Add :new here
    end
  end

  resources :posts do
    member do
      post :add_like
      delete :unlike
    end
  end

  resources :users do
    resources :posts do
      member do
        post :like
        delete :unlike
      end
    end
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  attribute :text, :text
  after_create :increment_post_comments_counter

  def increment_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :increment_post_likes_counter

  def increment_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments
  after_create :increment_user_posts_counter
  after_save :update_post_counter
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  attribute :title, :string
  attribute :text, :text
  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0
  def increment_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Attributes
  attribute :name, :string
  attribute :photo, :string
  attribute :bio, :text
  attribute :posts_counter, :integer, default: 0
  attribute :confirmed_at, :datetime, default: nil

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def init
    self.posts_counter ||= 0
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(_resource_or_scope)
    user_path(current_user)
  end

  def after_sign_up_path_for(_resource_or_scope)
    new_user_confirmation_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_user
  before_action :find_post

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user # Use 'current_user' instead of '@User'

    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.' }
        format.js # This will look for create.js.erb
      else
        format.html { render 'new' }
      end
    end
  end

  private

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def find_user
    @user = current_user
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_user_and_post

  def index
    @posts = @user.posts
  end

  def show; end

  def new
    @user = current_user
    @like = @post.likes.new
  end

  def like
    @like = @post.likes.new
    @like.author = current_user
    @like.save
    redirect_to user_post_path(@user, @post)
  end

  def unlike
    @like = @post.likes.find_by(post: @post)
    @like&.destroy
    redirect_to user_post_path(@user, @post)
  end

  private

  def find_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find_by(id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user, only: %i[index show like unlike]
  before_action :find_post, only: %i[show like unlike]

  def index
    @posts = @user.posts
  end

  def show
    @post = Post.includes(:comments, :author).find(params[:id])
  end

  def new
    @user = current_user
    @post = @user.posts.new
  end

  def like
    @like = @post.likes.new
    @like.author = current_user
    @like.save
    redirect_to user_post_path(@user, @post)
  end

  def unlike
    @like = @post.likes.find_by(post: @post)
    @like&.destroy
    redirect_to user_post_path(@user, @post)
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = 'Post created successfully.'
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_post
    @post = @user.posts.find_by(id: params[:id])
    return unless @post.nil?

    flash[:alert] = 'Post not found, back to posts page'
    redirect_to user_posts_path(@user)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @three_recent_posts = @user.recent_posts
  end

  def new; end

  def find_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Handle the situation when the post is not found
    flash[:alert] = 'User not found, back to users page'
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
// app/views/comments/create.js.erb

// Display an alert to indicate successful comment creation
alert('Comment created successfully!');

app/views/comments/new.html.erb
<h1>comments</h1>
<a href="<%= user_post_path(@user, @post) %>">
  <button id="back-btn">⬅</button>
</a>
<h1>Create a New Comment</h1>
<h2>Post <%= @post.id %></h2>
<h2>Current User <%= @user.name %></h2>

<%= form_with model: @comment, url: user_post_comments_path(@user, @post), local: true do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

<%= yield %>
</body>
</html>

app/views/likes/_like.js.erb
// Update like count
$('.like-count').text('<%= @post.likes_counter %> likes');

app/views/likes/_unlike.js.erb
// Update like count
$('.like-count').text('<%= @post.likes_counter %> likes');

app/views/posts/index.html.erb
<h1>Here is the Home page for user's posts</h1>

<a href="<%= user_path(@user) %>">
  <button id="back-btn">⬅</button>
</a>
<ul>
  <div class="user-box">
    <%= render partial: 'shared/user_photo', locals: { user: @user } %>
    <%= render partial: 'shared/user_deets', locals: { user: @user } %>
  </div>
  <% @posts.each do |post| %>
    <a href="<%= user_post_path(@user, post) %>">
      <div class="user-post">
        <div class="post">
          <h3>Post <%= raw "#" + post.id.to_s %></h3>
          <p><%= post.text %></p>
          <div class='post-interactions'>
            <span>Comments: <%= post.comments_counter %>,</span>
            <span>Likes: <%= post.likes_counter %></span>
          </div>
        </div>
        <h3>Comments:</h3>
        <% post.recent_comments.each do |comment| %>
          <div class="post-comments">
            <span><%= comment.author.name %>:</span>
            <span><%= comment.text %></span>
          </div>
        <% end %>
      </div>
    </a>
  <% end %>
  <a href="<%= new_user_post_path(@user, @post) %>" class='pagination'>
    <button id='pagination'>Create a new post</button>
  </a>
</ul>

app/views/posts/new.html.erb
<div class="container">
  <a href="<%= user_path(@user) %>">
    <button id="back-btn">⬅</button>
  </a>
  <h1>Create a New Post</h1>
  <%= form_with model: [@user, @post], local: true do |form| %>
    <div class="field">
      <%= form.label :title, class: "label" %>
      <%= form.text_field :title, class: "input" %>
    </div>    <div class="field">
      <%= form.label :text, class: "label" %>
      <%= form.text_area :text, class: "textarea" %>
    </div>    <div class="actions">
      <%= form.submit 'Create Post', class: "submit-btn" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Here are the specific posts by a user</h1>
<a href="<%= user_posts_path() %>">
  <button id="back-btn">⬅</button>
</a>
<h2>Post <%= "#" + @post.id.to_s %> by <%= @user.name %></h2>
<div class='post-interactions'>
  <span>Comments: <%= @post.comments_counter %>,</span>
  <span>Likes: <%= @post.likes_counter %></span>
</div>
<% if current_user.present? %>
  <div class="post-actions">
    <%= button_to "Like", like_user_post_path(@user, @post), method: :post, remote: true %>
    <%= button_to "Unlike", unlike_user_post_path(@user, @post), method: :delete, remote: true %>
  </div>
<% end %>
<p><%= @post.text %></p>
<h3>Comments:</h3>
<% @post.comments.each do |comment| %>
  <div class="post-comments">
    <span><%= comment.author.name %>:</span>
    <span><%= comment.text %></span>
  </div>
<% end %>
<a href="<%= new_user_post_comment_path(@user, @post) %>">
  <button id="back-btn">Add a comment</button>
</a>

<a href="<%= user_posts_path() %>">
  <button id="back-btn">Back to Posts</button>
</a>

app/views/shared/_user_deets.html.erb
<div class="user-details">
  <div class="user-name">
    <%= user.name %>
  </div>
  <div class="posts-count">
    <%= pluralize(user.posts.count, 'post' ) %>
  </div>
</div>

app/views/shared/_user_photo.html.erb
<% if user.photo.present? %>
  <div class="user-photo">
    <%= image_tag user.photo, alt: user.name %>
  </div>
<% else %>
  <div class="user-photo placeholder">
    No photo
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Here is the Home page for all users</h1>
<ul>
  <% @users.each do |user| %>
    <a href="<%= user_path(user) %>">
      <div class="user-box">
        <%= render partial: 'shared/user_photo', locals: { user: user } %>
        <%= render partial: 'shared/user_deets', locals: { user: user } %>
      </div>
    </a>

  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Here is the profile page and list of post by a specific users</h1>

<a href="<%= users_path %>">
  <button id="back-btn">⬅</button>
</a>
<a href="<%= user_posts_path(@user) %>">
  <div class="user-box">
    <%= render partial: 'shared/user_photo', locals: { user: @user } %>
    <%= render partial: 'shared/user_deets', locals: { user: @user } %>
  </div>

</a>
<div class="bio">
  <h3>Bio</h3>
  <p>
    <%= @user.bio %>
  </p>
</div>
<% @three_recent_posts.each do |post| %>
  <div class="post bio">
    <h3>Post <%= raw "#" + post.id.to_s %></h3>
    <p><%= post.text %></p>
    <div class='post-interactions'>
      <span>Comments: <%= post.comments_counter %>,</span>
      <span>Likes: <%= post.likes_counter %></span>
    </div>
  </div>
<% end %>
<a href="<%= user_posts_path(@user) %>">
  <button id="load-more-btn">See all posts</button>
</a>